// 组件注册
export {
  registerComponent,
  registerComponents,
  registerQuickComponent,
  getComponent,
  getQuickComponentConfig,
  hasComponent,
  getRegisteredComponentNames,
  parseQuickComponent,
  clearComponentRegistry,
  componentRegistry,
  quickComponentConfigs,
} from './componentRegistry';

// 只读渲染器注册
export {
  registerReadonlyRenderer,
  registerReadonlyRenderers,
  getReadonlyRenderer,
  hasReadonlyRenderer,
  getRendererByMode,
  resetReadonlyRenderers,
  getRegisteredRendererTypes,
  defaultRenderers,
  rendererRegistry,
  readonlyRegistry,
  // 渲染器函数
  textRenderer,
  textareaRenderer,
  optionRenderer,
  checkboxRenderer,
  switchRenderer,
  dateRenderer,
  timeRenderer,
  dateTimeRenderer,
  numberRenderer,
  percentageRenderer,
  currencyRenderer,
  jsonRenderer,
  imageRenderer,
  videoRenderer,
  fileRenderer,
  linkRenderer,
  phoneRenderer,
  emailRenderer,
  idCardRenderer,
  yesNoRenderer,
  maleFemaleRenderer,
  enableDisableRenderer,
  openCloseRenderer,
  statusRenderer,
} from './readonlyRegistry';
